### ISSUE TITLE
Sections 8.4 and 8.5: question about different source list in the Spec

### ISSUE THREAD

**Issue by nataliesus** [HMIS/LSASampleCode#707]
Hi!

The only difference between sections 8.4 and 8.5 is the [SystemPath] usage.

But why 8.4 Source List is 6 elements longer than 8.5 Source List?
![image](https://user-images.githubusercontent.com/28144855/137102845-a2856c08-b927-4363-a035-bab7d54477e0.png)

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
In section 8.5, average days are only reported by system path for pop IDs 0-17 - and the criteria for those populations doesn't include the population identifiers HHDisability, HHFleeingDV, AC3Plus, HoHRace, (etc...) that are needed for section 8.4.  

(The differences are masked in the sample code because it uses the ref_RowValues, ref_RowPopulations and tlsa_AveragePops tables rather than writing separate queries for 8.4 and 8.5.)

If this doesn't answer your question -- I think I might be missing something -- please re-open!

Thank you.
