### ISSUE TITLE
11.2 Set Homeless1 and 3 values issue due to Enrollment.csv plus code

### ISSUE THREAD

**Issue by 2008zjqc** [HMIS/LSASampleCode#766]
Hi Molly,

There is an common issue with data set in HMIS csv they provided. For instance, in the enrollment.csv PreviousStreetESSH which should may only applicable for Living situations not like (16,1,8). But in the enrollment.csv. there are couple records such living situation but with 99 as PreviousStreetESSH, such as EnrollmentID='169584' and person ID='62281' and another one with enrollmentID='171802_23766' an PersonID='171802'. Those PreviousStreetESSH should all be NULL. 

With such data, in 11.2 while set values for HomelessDate 1 and HomelessDate 3, those data is no long PreviousStreeESSH is NULL anymore. Our end, for such answer, we treat it as bad data, in other words, even though they provide some answer, we will treat them as NULL. Then, our report output is different with LSA provided report output for this case. 

Also there are similar issue with 3.917 other questions. Some of them, they definitely can't provide answers according to the data dictionary. But in the Enrollment.CSV the have answers. And LSA code just treat them as valid ones. Please advise on how to handle such type of issue. Thanks.
Best,
Chen

**Comment by MollyMcEvilley** [comment]
I agree with you that since _PreviousStreetESSH_ is a dependent field, I would kind of expect it to be NULL unless the values in _LivingSituation_ and _LengthOfStay_ require that it be collected -- so I don't think this is a bug in the sample code.  BUT the HMIS CSV specs don't require that -- so it's not a bug in the sample data... 

For the sake of simplicity, it's easy enough to change `PreviousESSHStreet = 1` to `PreviousESSHStreet <> 0` in those sections of the code for HomelessDate1 and HomelessDate3, so I'm going to go ahead and do that.

**Comment by nataliesus** [comment]
Hi @MollyMcEvilley ,

Now there is a discrepancy between Sample Code and Spec after `PreviousESSHStreet = 1` was changed to `PreviousESSHStreet <> 0`.

Spec still has `PreviousESSHStreet = 1` as an option:
![image](https://user-images.githubusercontent.com/28144855/139046753-13493ea2-aa34-43f9-bfbb-73690a9c8356.png)

Best regards,
Natalie
