### ISSUE TITLE
Step 8.4-8.7 Average Days from LSAHousehold -- tlsa_Household has lowercase h

### ISSUE THREAD

**Issue by kcourtneywellsky** [HMIS/LSASampleCode#771]
In Step 8.4-8.7 Average Days from LSAHousehold, the "from" clause uses table name "tlsa_household". Since table names in some DBMSs like MS SQL Server are case-sensitive, this could result in the query inserting no data. Please change this to "tlsa_Household". This will also be consistent with its spelling in the rest of the sample code.

Location of change:
File: 08 LSACalculated Averages for LSAHousehold and LSAExit.sql
Line 263: " from tlsa_household hh "

Change request:
Line 263: " from tlsa_Household hh "

**Comment by MollyMcEvilley** [comment]
Thanks for an easy one, Kern.  :)

**Comment by nataliesus** [comment]
Hi @kcourtneywellsky and @MollyMcEvilley ,

We don't have problem with case-sensitive table/column names, but if it is important for you - there are several more places to fix:

- tlsa_hhid (instead of tlsa_HHID)
![image](https://user-images.githubusercontent.com/28144855/139043340-d1ff95f8-219e-4ca1-953b-99139a780cbf.png)
- ahar (instead of AHAR)
![image](https://user-images.githubusercontent.com/28144855/139043648-cf8b981f-e578-4a2c-871e-c0dcfdc60f98.png)
- popID (instead of popID)
![image](https://user-images.githubusercontent.com/28144855/139045152-03bb2528-f2e2-44ab-a437-7ee36feb8317.png)


Best regards,
Natalie
